git checkout --theirs	kinetic-dataset/1G99_WT/L01.mol2
git checkout --theirs	kinetic-dataset/1G99_WT/L02.mol2
git checkout --theirs	kinetic-dataset/1T7Q_WT/L01.mol2
git checkout --theirs	kinetic-dataset/1T7Q_WT/L02.mol2
git checkout --theirs	kinetic-dataset/1T7Q_WT/cmd
git checkout --theirs	kinetic-dataset/1T7Q_WT/constraints.txt
git checkout --theirs	kinetic-dataset/1T7Q_WT/production.pdb
git checkout --theirs	kinetic-dataset/1TEX_WT/L01.mol2
git checkout --theirs	kinetic-dataset/1TEX_WT/L02.mol2
git checkout --theirs	kinetic-dataset/1TEX_WT/cmd
git checkout --theirs	kinetic-dataset/1TEX_WT/production.pdb
git checkout --theirs	kinetic-dataset/2DG5_WT/L01.mol2
git checkout --theirs	kinetic-dataset/2DG5_WT/production.pdb
git checkout --theirs	kinetic-dataset/2NO7_WT/L02.mol2
git checkout --theirs	kinetic-dataset/2NO7_WT/production.pdb
git checkout --theirs	kinetic-dataset/3PNK_WT/L01.mol2
git checkout --theirs	kinetic-dataset/3PNK_WT/L02.mol2
git checkout --theirs	kinetic-dataset/3PNK_WT/production.pdb
git checkout --theirs	kinetic-dataset/3SGV_WT/L01.mol2
git checkout --theirs	kinetic-dataset/3SGV_WT/L02.mol2
git checkout --theirs	kinetic-dataset/3SGV_WT/production.pdb
git checkout --theirs	kinetic-dataset/3UIE_WT/L01.mol2
git checkout --theirs	kinetic-dataset/3UIE_WT/L02.mol2
git checkout --theirs	kinetic-dataset/3UIE_WT/production.pdb
git checkout --theirs	kinetic-dataset/4B8R_WT/L01.mol2
git checkout --theirs	kinetic-dataset/4B8R_WT/L02.mol2
git checkout --theirs	kinetic-dataset/4B8R_WT/production.pdb
git checkout --theirs	kinetic-dataset/4FIX_WT/L01.mol2
git checkout --theirs	kinetic-dataset/4FIX_WT/L02.mol2
git checkout --theirs	kinetic-dataset/4FIX_WT/production.pdb
git checkout --theirs	kinetic-dataset/6Q3W_WT/production.pdb
