git checkout --theirs kinetic-dataset/6Q3W_WT/production.pdb
git checkout --theirs kinetic-dataset/4FIX_WT/L01.mol2
git checkout --theirs kinetic-dataset/3UIE_WT/production.pdb
git checkout --theirs kinetic-dataset/3PNK_WT/production.pdb
git checkout --theirs kinetic-dataset/3PNK_WT/L02.mol2
git checkout --theirs kinetic-dataset/3PNK_WT/L01.mol2
git checkout --theirs kinetic-dataset/1TEX_WT/production.pdb
git checkout --theirs kinetic-dataset/1TEX_WT/cmd
git checkout --theirs kinetic-dataset/1T7Q_WT/cmd
